configuration: 
  name: hellobioqa
  author: oaqa
  
persistence-provider:
  inherit: helloqa.db.local-persistence-provider

collection-reader:
  inherit: hellobioqa.collection.decorated-collection-reader
  dataset: TRECGEN06
  file: /input/trecgen06.txt

pipeline:
  - inherit: jdbc.sqlite.cse.phase  
    name: keyterm-extractor
    options: |
      #- inherit: helloqa.keyterm.simple
      #- inherit: hellobioqa.team10.keyterm.bdutt-simple
      #- inherit: hellobioqa.team10.keyterm.alkesh-simple
      #- inherit: hellobioqa.team10.keyterm.yifeih-simple
      #- inherit: hellobioqa.team10.keyterm.zeyuanl-simple
      - inherit: hellobioqa.keyterm.simple
      
  - inherit: jdbc.sqlite.cse.phase 
    name: retrieval-strategist
    options: |
      #- inherit: hellobioqa.retrieval.simple-solr-strategist
      - inherit: hellobioqa.team10.retrieval.alkesh-synonyms-solr-strategist
      #- inherit: hellobioqa.retrieval.zeyuanl-solr-strategist
      #- inherit: hellobioqa.retrieval.zeyuanl-phrase-strategist
          
  - inherit: jdbc.sqlite.cse.phase  
    name: passage-extractor
    options: |
      #- inherit: hellobioqa.passage.simple
      - inherit: hellobioqa.team10.passage.alkesh-solr-leganspan-passage
      #- inherit: hellobioqa.passage.solrpassage
      
  - inherit: helloqa.eval.keyterm-aggregator-consumer

  - inherit: internal.eval.cse-retrieval-aggregator-consumer
  - inherit: internal.eval.cse-passage-map-aggregator-consumer

post-process: 
  - inherit: internal.eval.cse-retrieval-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: internal.report.f-measure-report-component
  - inherit: internal.eval.cse-passage-map-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: internal.report.map-report-component